language: java
jdk:
- oraclejdk11
before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo
  tee /etc/hosts
- cat /etc/hosts
script:
- mvn -Dtest=AllTestsNoChrX test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  slack:
    on_success: always
    on_failure: always
    secure: X2TRbGQGMqYnoC4KucYphXf/qDdiyvUbqvWevpPFu7s+wt+cCnwIZw7Y3Wx24LTxj9XB41XN/nXvuf+izTQne6AjfEZYISFr4l5GmLGqHWggzKg0UC7X+Sbzio1wHM8WX79hC1p8xDiAtZdHQDEUyRl/bnjVJ+ts2tdgED4KKdiEJb9Ni+4j9Zj/d3UQeGDB7bZCgeavf/WrF2w7s7IhG+Vm/zRv5AT+WtRzOqFXJdrBSGT5+uIDD27gDDH9uPhTOzz0IPX3O2YkJYvH+fzgwrAULtVjtPI+7mHTv3ltCD3G7Mx4W+FaKj+WRG1QBNgz8LWN+m1p2gIKIV9zZIGqX7POu5zWXlS8hjfDSX1t20fyrMOs4Os06A30hOMHrUogaeNkx+tughykWExCVnyGcKx426MgAAMOW4IE3wqU978ev5mLfqOtRocpZmCdtgpfchz4UQnFOofzg1NM5CHIt9s+ZYQp2lmgqEVY1ejBYYlQ2COeiYPnm5c9VG6F7YS/Fu85LI8E6Shvl41Z5omy6//1XV06SIvopRBn/Qjtz8CM3pnvSxwZJ37h/XU2r/7CdmKkDadUdVrA5Pg2DoF9XA63nRRsgxLqy/bGojaVtpy1NTKmOaikvaKfvnAhHdICqEqjbDihwNkEVRkGNFYMJOmE3402tC4Hb+nb41irM7o=
deploy:
  provider: releases
  api_key:
    secure: E7WTXvqqk32EjdwF0bJnREsfa2kVclgkgf5KHS9HJMyKKqKkUAA7SICuV0fS+IrIEh3KHNdrDy4bE+J9dX2hwidyjomTMM6JlGzOlGBK6p8rlPmlutIDlxMGx25Q7J2griLVrSnX/p6Wd1FXLGhh/g3DTLXqgJGBFrAl+uvuMRWlD2XdcWUq4VEuFEiHAtISqqT0t73TWobgSkxD+KyFnhk+BfiZePXHtjAtvn17S2Om6V4rRaG3gad7F1Gp/39qOPn3IqpHTA02FIME7PwiUMr/Pc7fT7/F58Tr9ergdMfLcHGugnqJr3GwUOvFrT6XPxtqfwzqBOXjzqvjaLzBAq66sVmjtyqTXY7hc89QHU863SWGcuVbUC2AOsHjXzm9lVYftbMO7br92DZsV06HP/WondOvIUil3TIcKnIAagH/5lIoSIk05SQ4wytPjXJQRJNA2HXUC/o+52ivJuwGZrg9pR2rpXgm0YWEccMfM1anoc/WVThr7R7U6O6kOau6rA1zptQh4ZFD2ROMLCV/b2n8VWPCuGRzqcvdq3LH7hyTRyplXKiUVerlz1MZqEdaSzj3gCytTBZW5SBD2s5olJ4k8VQ9E22z0pJ91Ud5VJvmQvfUIMH35zdJg2fc2O+bq5P15kWf3GxvxtYUIyCqXwGC4wgJgPTj0HKt3SVMIsc=
  skip_cleanup: true
  file: target/imputationserver.zip
  on:
    tags: true
