language: java
jdk:
- oraclejdk11
before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo
  tee /etc/hosts
- cat /etc/hosts
script:
- mvn -Dtest=AllTestsNoChrX test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  slack:
    on_success: always
    on_failure: always
    secure: X2TRbGQGMqYnoC4KucYphXf/qDdiyvUbqvWevpPFu7s+wt+cCnwIZw7Y3Wx24LTxj9XB41XN/nXvuf+izTQne6AjfEZYISFr4l5GmLGqHWggzKg0UC7X+Sbzio1wHM8WX79hC1p8xDiAtZdHQDEUyRl/bnjVJ+ts2tdgED4KKdiEJb9Ni+4j9Zj/d3UQeGDB7bZCgeavf/WrF2w7s7IhG+Vm/zRv5AT+WtRzOqFXJdrBSGT5+uIDD27gDDH9uPhTOzz0IPX3O2YkJYvH+fzgwrAULtVjtPI+7mHTv3ltCD3G7Mx4W+FaKj+WRG1QBNgz8LWN+m1p2gIKIV9zZIGqX7POu5zWXlS8hjfDSX1t20fyrMOs4Os06A30hOMHrUogaeNkx+tughykWExCVnyGcKx426MgAAMOW4IE3wqU978ev5mLfqOtRocpZmCdtgpfchz4UQnFOofzg1NM5CHIt9s+ZYQp2lmgqEVY1ejBYYlQ2COeiYPnm5c9VG6F7YS/Fu85LI8E6Shvl41Z5omy6//1XV06SIvopRBn/Qjtz8CM3pnvSxwZJ37h/XU2r/7CdmKkDadUdVrA5Pg2DoF9XA63nRRsgxLqy/bGojaVtpy1NTKmOaikvaKfvnAhHdICqEqjbDihwNkEVRkGNFYMJOmE3402tC4Hb+nb41irM7o=
deploy:
  provider: releases
  api-key:
    secure: rW+m4s/QTepeTfYIf3iHORYXi5J9y2iHL6We7o4XrVibIEchg7o7xTInQ1VOAL03+5Om6qGX55vpXRpFiV5SraBdi9uYQvuDwJ2+U+rnYkdWLr7wqXWPmTlZMmfN8Nhpgd+WwnCYA624Ehep/G9PIYjvL/HQII7VvBkK/idpNhu4I1WBEkQ3zSyOaO8NHB6w2nuzdYOkRv9kQFldBKk7Y33oxgzyT0RJq7lmqkxg8LfiF1BGNGakxhlNdj4DjqiYZr0s/+8D2Ao+1PChXeJxGH0FlzHFPPchpxcrCp2gQxvEaMcwOlFw1/hPWX6V3M6GPU7I2X0/9FkQ5d4gfHf36o+FfQqEQIomMMfrtnI5fbVVfl8DpjTZCMSy7zeZLSvlV2JEt5SSk8zXQJP+0CgKAyqrRKJmJdo9JGdWDJbdfftM+lwBpL5epSNTFfqIFv66GHSiiFWzsE2qpzUfh3Ov9frfj+pO3Hr23Sxz+swC974ZMV4+wYJkla4wHQKod7wscAOxB8xyoJ3uSuhitWyrwiTteinvkm8yi3Gdrk/p+SOIp77DJQo12GkBByTqzV+gZKUiY1zA4E24BK9RgliOz5wJ5PG7+BCiA+/yM73if/xdWRfo0ZLxD/g2PqTjI29pH/+SR+dAG63SSsWNQKHkc4MMRAiNggLJcf4u7BjrkTQ=
  skip_cleanup: true
  file: target/imputationserver.zip
  on:
    tags: true
