site_name: TOPMed Imputation Server
theme: readthedocs

pages:
- Home: index.md
- Getting Started: getting-started.md
- Data Preparation: prepare-your-data.md
- Reference Panels: reference-panels.md
- Pipeline Overview: pipeline.md
- Security: data-sensitivity.md
- FAQ: faq.md
- Developer Documentation:
  - API: api.md
  - Docker: docker.md
  - Create Reference Panels: create-reference-panels.md
- Contact: contact.md



repo_name: statgen/imputationserver
repo_url: https://github.com/statgen/imputationserver
edit_uri: edit/master/docs

extra:
  social:
    - type: github-alt
      link: https://github.com/statgen/imputationserver
    - type: twitter
      link: https://twitter.com/umimpute

markdown_extensions:
    - toc:
        permalink:
    - admonition:
